language: php
php:
  - 7.2

env:
    - APP_ENV=dev GTAG_ID=dummy

  # Update composer
before-install:
    - composer self-update

install:
    - composer install

  # Run script
script:
    - bin/phpunit
